[build]
builder = "nixpacks"
buildCommand = "yarn cache clean && rm -rf node_modules && yarn install --no-immutable && yarn build"

[deploy]
startCommand = "yarn start"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
port = 3000
numReplicas = 1

# Временно отключаем мониторинг для стабильного деплоя
#[monitoring]
#enabled = true
#metrics = [
#    "cpu",
#    "memory",
#    "disk",
#    "response-time"
#]
#alerts = [
#    { type = "cpu", threshold = 80, duration = "5m" },
#    { type = "memory", threshold = 80, duration = "5m" },
#    { type = "disk", threshold = 80, duration = "5m" },
#    { type = "response-time", threshold = 1000, duration = "5m" }
#] 