[build]
builder = "nixpacks"
buildCommand = "yarn install --immutable && yarn build"
watchPatterns = ["src/**/*", "package.json", "yarn.lock"]

[deploy]
startCommand = "yarn start"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
port = 3000
numReplicas = 1
healthcheckInterval = 30

[nixpacks]
node-version = "20.11.0"
yarn-version = "4.6.0"

# Временно отключаем мониторинг для стабильного деплоя
#[monitoring]
#enabled = true
#metrics = [
#    "cpu",
#    "memory",
#    "disk",
#    "response-time"
#]
#alerts = [
#    { type = "cpu", threshold = 80, duration = "5m" },
#    { type = "memory", threshold = 80, duration = "5m" },
#    { type = "disk", threshold = 80, duration = "5m" },
#    { type = "response-time", threshold = 1000, duration = "5m" }
#] 