[build]
builder = "nixpacks"
buildCommand = "yarn build"

[deploy]
startCommand = "yarn start"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on-failure"
restartPolicyMaxRetries = 3

[monitoring]
enabled = true
metrics = [
    "cpu",
    "memory",
    "disk",
    "response-time"
]
alerts = [
    { type = "cpu", threshold = 80, duration = "5m" },
    { type = "memory", threshold = 80, duration = "5m" },
    { type = "disk", threshold = 80, duration = "5m" },
    { type = "response-time", threshold = 1000, duration = "5m" }
] 